### ISSUE TITLE
kola: manual test jenkins job against AWS

### ISSUE THREAD

**Issue by philips** [coreos/mantle#105]
To have parity with the release tests that we are running today we need to run against a set of hosts on AWS. Steps:

- [x] Setup up a "manual AWS jenkins job" that takes an existing AMI as a parameter, write docs on how to do this
- [ ] Setup a job that can look at AMI ids for a release on the release mirror and run the AWS tests
- [ ] Setup a job that can look at AMI ids for a release on a private release URL and run the AWS tests

**Comment by mischief** [comment]
@philips can you clarily the first item? what docs need to be written? i set up a parameterized jenkins build called kola-aws.

what about the second item? is the intention here to take a region+release channel and derive an ami id from that?

**Comment by marineam** [comment]
@mischief the gist of that last item was to make the job more automatic, so have some mechanism for the job to launch automatically after running the oem/ami/import.sh script.

Probably two ways:
 - Upload the ami-wathever.txt files for the region used for the import in import.sh instead of waiting for the later publish step which does the rest. This would be posting to gs://build.release...blah which is private so the jenkins poll job would need to be able to handle that.
 - Alternatively we transition to importing AMIs to jenkins before we get the import code written in code. This will mean running the existing (perhaps with some tweaks) import.sh script in the jenkins container. We would need to add all the AWS/EC2 tools to the jenkins container to support it and run a jenkins slave on AWS or GCE or other location with sufficient bandwidth to upload/download images.

**Comment by philips** [comment]
@mischief Can you just make a oneliner or a script that someone can call. The input would be an ami id and region. For example `test-ami ami-76bbba6b eu-central-1` and then it should dump out the build URL to watch.

**Comment by marineam** [comment]
For releases: jenkins tests run in dev right? so we need to share the to-be-tested AMI created by `import.sh` with the dev account before the jenkins job can actually do anything with it.

**Comment by crawford** [comment]
The two remaining tasks are infra issues.
