### ISSUE TITLE
kola: test automatically against GCE

### ISSUE THREAD

**Issue by philips** [coreos/mantle#123]
@pbx0 can you edit this and add in your tasks.

**Comment by pbx0** [comment]
Kola job is up and triggering on on new builds being pushed. https://github.com/coreos/mantle/pull/128 is the last PR needed for it to run smoothly. 

Next steps are figuring out https://github.com/coreos/mantle/pull/115 so that fleet failures no-longer show up. This affects all kola platforms. Once this is sorted, slack notifications will be enabled on failures.
