### ISSUE TITLE
Validate longer resource IDs in AWS

### ISSUE THREAD

**Issue by arithx** [coreos/mantle#851]
In July 2018 AWS is switching to longer resource IDs (https://aws.amazon.com/ec2/faqs/#longer-ids). We should validate that we are not affected before the release.

[This page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html) has instructions for opting an account into the longer resource IDs that we could use for testing purposes.

**Comment by dustymabe** [comment]
@sayanchowdhury  FYI.. @arithx we are doing validation for our fedimg tool over here: https://github.com/fedora-infra/fedimg/issues/122

we'd like to consolidate tooling in the future so it's good to keep you both in the loop

**Comment by euank** [comment]
I'm pretty confident we don't have any places where we make such assumptions, so in all likelyhood this issues won't require any work.

It's probably reasonable to switch our dev account over right after a release to give us a week to fix it in the unlikely event that nightlies suddenly break.

I think there's a fair argument to be made for leaving our release account on the old length for as long as possible to avoid breaking any CL users who are parsing our IDs wrongly for as long as possible.

**Comment by dustymabe** [comment]
> I think there's a fair argument to be made for leaving our release account on the old length for as long as possible to avoid breaking any CL users who are parsing our IDs wrongly for as long as possible.

That's fair, but it's going to happen pretty soon as the AWS deadline is July 2018. I'd say sending out communications about it and having it switch over a few weeks before July would be ideal.

**Comment by euank** [comment]
I'm hopeful that AWS has done their job of communicating a date and impact widely themselves... probably better than we can.

Since users have already been told by AWS that "on this date, new images will start having long ids", it seems mildly less surprising if that's true for us as well.

If shifting it a few weeks makes it line up better with release ordering (e.g. it impacts an alpha, then beta, then stable image in that order vs releasing all at once with long ids) that seems like a good reason to do it a bit early.
Other than that, I can't think of a good reason to switch the prod account over early.

**Comment by arithx** [comment]
So far I've used longer resource IDs for most compute resources used by `kola` without encountering any issues.

**Comment by arithx** [comment]
Closing as the deadline has passed and nothing is breaking.
